---
swagger: "2.0"
info:
  description: "NFVO module service for the NI project."
  version: "1.0.0"
  title: "NI-NFVO"
  contact:
    email: "vantu.bkhn@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
schemes:
- "http"
paths:
  /sfcrs:
    get:
      tags:
      - "sfcr"
      summary: "Get currently active SFC requests."
      operationId: "get_sfcrs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SFCR"
      x-swagger-router-controller: "ni_nfvo.controllers.sfcr_controller"
    post:
      tags:
      - "sfcr"
      summary: "Add new SFC request. return sfcr ID if success"
      operationId: "add_sfcr"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "sfcr_spec"
        description: "SFC request object to be added."
        required: true
        schema:
          $ref: "#/definitions/SFCRSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "ni_nfvo.controllers.sfcr_controller"
  /sfcrs/{id}:
    delete:
      tags:
      - "sfcr"
      summary: "Delete a sfcr."
      description: ""
      operationId: "del_sfcr"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "route id"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.sfcr_controller"
  /routes:
    get:
      tags:
      - "route"
      summary: "Get current route information, i.e., list of all active SFCRs including\
        \ their paths."
      description: ""
      operationId: "get_routes"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "Success."
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Route"
      x-swagger-router-controller: "ni_nfvo.controllers.route_controller"
    post:
      tags:
      - "route"
      summary: "Route a request via the provided route. Return route ID if success."
      description: ""
      operationId: "set_route"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "route_spec"
        description: "Route information including SFCR ID and vnf instance ids."
        required: true
        schema:
          $ref: "#/definitions/RouteSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
        "400":
          description: "Invalid parameters supplied."
      x-swagger-router-controller: "ni_nfvo.controllers.route_controller"
  /routes/{id}:
    put:
      tags:
      - "route"
      summary: "Update a new route path or new sfcrs."
      description: ""
      operationId: "update_route"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "route id"
        required: true
        type: "string"
      - in: "body"
        name: "route_update_spec"
        description: "Route Update info."
        required: true
        schema:
          $ref: "#/definitions/RouteUpdateSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "ni_nfvo.controllers.route_controller"
    delete:
      tags:
      - "route"
      summary: "Delete a Route."
      description: ""
      operationId: "del_route"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "route id"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.route_controller"
  /vnfs:
    post:
      tags:
      - "vnf"
      summary: "Instantiate an instance of a VNF flavor on a given node. Return vnf\
        \ ID if success"
      operationId: "deploy_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "vnf_spec"
        description: "Flavor of VNF instance to be deployed as well as the target\
          \ node."
        required: true
        schema:
          $ref: "#/definitions/VNFSpec"
      responses:
        "200":
          description: "Success."
          schema:
            type: "string"
      x-swagger-router-controller: "ni_nfvo.controllers.vnf_controller"
  /vnfs/{id}:
    delete:
      tags:
      - "vnf"
      summary: "Destroy a VNF instance."
      description: ""
      operationId: "destroy_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "vnf id"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.vnf_controller"
  /vnfs/{id}/shutdown:
    post:
      tags:
      - "vnf"
      summary: "Shut down a VNF instance."
      description: ""
      operationId: "shutdown_vnf"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of VNF instance to be shut down."
        required: true
        type: "string"
      responses:
        "200":
          description: "Success."
      x-swagger-router-controller: "ni_nfvo.controllers.vnf_controller"
definitions:
  SFCRSpec:
    type: "object"
    required:
    - "source_client"
    properties:
      name:
        type: "string"
      source_client:
        type: "string"
        description: "the id of the source VM (not VNF)"
      destination_client:
        type: "string"
        description: "the id of the destination VM (not VNF)"
      src_ip_prefix:
        type: "string"
      dst_ip_prefix:
        type: "string"
      src_port_min:
        type: "integer"
        format: "int32"
      src_port_max:
        type: "integer"
        format: "int32"
      dst_port_min:
        type: "integer"
        format: "int32"
      dst_port_max:
        type: "integer"
        format: "int32"
      proto:
        type: "string"
      bw:
        type: "integer"
        format: "int32"
        description: "bandwidth requirement of the sfcr"
      delay:
        type: "integer"
        format: "int32"
        description: "delay requirement of the sfcr"
      duration:
        type: "integer"
        format: "int32"
        description: "sfcr running duration"
      nf_chain:
        type: "array"
        description: "the type of VNFs in the path (e.g.: fw, ids, nat, etc.)."
        items:
          type: "string"
    description: "Specification to create new SFC request. src/dst ip prefix, src/dst\
      \ port min/max, proto are for traffic classification"
    example:
      src_port_max: 6
      source_client: "source_client"
      destination_client: "destination_client"
      dst_ip_prefix: "dst_ip_prefix"
      nf_chain:
      - "nf_chain"
      - "nf_chain"
      src_ip_prefix: "src_ip_prefix"
      src_port_min: 0
      duration: 7
      dst_port_min: 1
      delay: 2
      bw: 5
      proto: "proto"
      name: "name"
      dst_port_max: 5
  SFCR:
    type: "object"
    properties:
      id:
        type: "string"
      arrivaltime:
        type: "string"
        format: "date-time"
      name:
        type: "string"
      source_client:
        type: "string"
        description: "the id of the source VM (not VNF)"
      destination_client:
        type: "string"
        description: "the id of the destination VM (not VNF)"
      src_ip_prefix:
        type: "string"
      dst_ip_prefix:
        type: "string"
      src_port_min:
        type: "integer"
        format: "int32"
      src_port_max:
        type: "integer"
        format: "int32"
      dst_port_min:
        type: "integer"
        format: "int32"
      dst_port_max:
        type: "integer"
        format: "int32"
      proto:
        type: "string"
      bw:
        type: "integer"
        format: "int32"
        description: "bandwidth requirement of the sfcr"
      delay:
        type: "integer"
        format: "int32"
        description: "delay requirement of the sfcr"
      duration:
        type: "integer"
        format: "int32"
        description: "sfcr running duration"
      nf_chain:
        type: "array"
        description: "the type of VNFs in the path (e.g.: fw, ids, nat, etc.)."
        items:
          type: "string"
    description: "SFC request."
    example:
      src_port_max: 6
      source_client: "source_client"
      destination_client: "destination_client"
      dst_ip_prefix: "dst_ip_prefix"
      nf_chain:
      - "nf_chain"
      - "nf_chain"
      src_ip_prefix: "src_ip_prefix"
      src_port_min: 0
      duration: 7
      dst_port_min: 1
      delay: 2
      bw: 5
      proto: "proto"
      arrivaltime: "2000-01-23T04:56:07.000+00:00"
      name: "name"
      id: "id"
      dst_port_max: 5
  RouteSpec:
    type: "object"
    required:
    - "sfcr_ids"
    - "vnf_instance_ids"
    properties:
      sfc_name:
        type: "string"
      sfcr_ids:
        type: "array"
        items:
          type: "string"
      vnf_instance_ids:
        type: "array"
        description: "list of list of vnf id(s). Each sub-list is a node in traffic\
          \ path, where traffic are load-balanced between VNFs in the node. Each E.g.:\
          \ [[A,B], [C], [D]] : traffic go to [A, B] node (load-balanced between A\
          \ and B), then go to C, then go to D."
        items:
          type: "array"
          items:
            type: "string"
      is_symmetric:
        type: "boolean"
    description: "Specficiation to create routing information for given SFCR ID(s)"
    example:
      vnf_instance_ids:
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      is_symmetric: true
      sfc_name: "sfc_name"
      sfcr_ids:
      - "sfcr_ids"
      - "sfcr_ids"
  Route:
    type: "object"
    properties:
      id:
        type: "string"
      sfc_name:
        type: "string"
      sfcr_ids:
        type: "array"
        items:
          type: "string"
      vnf_instance_ids:
        type: "array"
        description: "list of list of vnf id(s). Each sub-list is a node in traffic\
          \ path, where traffic are load-balanced between VNFs in the node. Each E.g.:\
          \ [[A,B], [C], [D]] : traffic go to [A, B] node (load-balanced between A\
          \ and B), then go to C, then go to D."
        items:
          type: "array"
          items:
            type: "string"
      is_symmetric:
        type: "boolean"
    description: "Detailed routing (SFC) information."
    example:
      vnf_instance_ids:
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      is_symmetric: true
      sfc_name: "sfc_name"
      id: "id"
      sfcr_ids:
      - "sfcr_ids"
      - "sfcr_ids"
  RouteUpdateSpec:
    type: "object"
    properties:
      sfcr_ids:
        type: "array"
        items:
          type: "string"
      vnf_instance_ids:
        type: "array"
        description: "each sub-list represent a node on the traffic path. each node\
          \ is a list of vnf instances, where traffic are load-balanced"
        items:
          type: "array"
          items:
            type: "string"
    description: "Specification to update the path of a route."
    example:
      vnf_instance_ids:
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      - - "vnf_instance_ids"
        - "vnf_instance_ids"
      sfcr_ids:
      - "sfcr_ids"
      - "sfcr_ids"
  VNFSpec:
    type: "object"
    required:
    - "flavor_id"
    properties:
      flavor_id:
        type: "string"
      node_name:
        type: "string"
        description: "name of the compute node where VNF will be deployed"
      vnf_name:
        type: "string"
      user_data:
        type: "string"
        description: "configuration to pass to the VNF at boot (e.g., cloud-init)"
    description: "specification to deploy VNF."
    example:
      flavor_id: "flavor_id"
      node_name: "node_name"
      vnf_name: "vnf_name"
      user_data: "user_data"
externalDocs:
  description: "Find out more about DPNM NI."
  url: "http://dpnm.postech.ac.kr/"
